
INSERT INTO City (nameCity) VALUES ('Ibague'), ('Bogota'), ('Nueva York'), ('Cali');

INSERT INTO CurrentWeather (ObservationTime, 
	Temperature, WeatherDescription, WindSpeed,
	WindDegree, windDir, Pressure, Precip, 
	HumidiTy, CloudOver, Feelslike, Visibility, CityId) VALUES 
	('2020-13-06 22:20:09',
	13,
	'Hot',
	0,
	349,
	'N',
	1010,
	0,
	90,
	0,
	13,
	16,
	1),
	('2020-13-06 22:20:09',
	5,
	'Cold',
	0,
	349,
	'S',
	1010,
	0,
	90,
	0,
	13,
	16,
	2),
	('2020-13-06 22:20:09',
	30,
	'Sunny',
	0,
	349,
	'N',
	1010,
	0,
	90,
	0,
	13,
	16,
	3),
	('2020-13-06 22:20:09',
	13,
	'Hot',
	0,
	349,
	'S',
	1010,
	0,
	90,
	0,
	13,
	16,
	4),
	('2020-13-06 22:20:09',
	13,
	'Hot',
	0,
	349,
	'N',
	1010,
	0,
	90,
	0,
	13,
	16,
	5)

	INSERT INTO News (Author, Title, Description, Url, UrlToImage, PublishedAt, Content, CityId) VALUES 
	('Tyler Durden', 'Narrative Control Operations Escalate As America Burns',
	'Narrative Control Operations Escalate As America Burns\n\n Tyler Durden\n \nSat, 06/13/2020 - 21:30\n\n Authored by Caitlin Johnstone via Medium.com,\r\n\n\nWikipedia, Facebook, Twitter, and mainstream media are falling all over themselves with censorship and spin jobs…',
	'https://www.zerohedge.com/political/narrative-control-operations-escalate-america-burns',
	'https://zh-prod-1cc738ca-7d3b-4a72-b792-20bd8d8fa069.storage.googleapis.com/s3fs-public/styles/max_650x650/public/2020-06/1_7LdK4cup8c8xRQzggtaP5Q.png?itok=Mvt-AQoZ',
	'2020-06-14T01:30:00Z',
	'Authored by Caitlin Johnstone via Medium.com,\r\nWikipedia, Facebook, Twitter, and mainstream media are falling all over themselves with censorship and spin jobs to get the narrative back under control… ',
	1),
	('Tyler Durden', 'Narrative Control Operations Escalate As America Burns',
	'Narrative Control Operations Escalate As America Burns\n\n Tyler Durden\n \nSat, 06/13/2020 - 21:30\n\n Authored by Caitlin Johnstone via Medium.com,\r\n\n\nWikipedia, Facebook, Twitter, and mainstream media are falling all over themselves with censorship and spin jobs…',
	'https://www.zerohedge.com/political/narrative-control-operations-escalate-america-burns',
	'https://zh-prod-1cc738ca-7d3b-4a72-b792-20bd8d8fa069.storage.googleapis.com/s3fs-public/styles/max_650x650/public/2020-06/1_7LdK4cup8c8xRQzggtaP5Q.png?itok=Mvt-AQoZ',
	'2020-06-14T01:30:00Z',
	'Authored by Caitlin Johnstone via Medium.com,\r\nWikipedia, Facebook, Twitter, and mainstream media are falling all over themselves with censorship and spin jobs to get the narrative back under control… ',
	2),
	('Tyler Durden', 'Narrative Control Operations Escalate As America Burns',
	'Narrative Control Operations Escalate As America Burns\n\n Tyler Durden\n \nSat, 06/13/2020 - 21:30\n\n Authored by Caitlin Johnstone via Medium.com,\r\n\n\nWikipedia, Facebook, Twitter, and mainstream media are falling all over themselves with censorship and spin jobs…',
	'https://www.zerohedge.com/political/narrative-control-operations-escalate-america-burns',
	'https://zh-prod-1cc738ca-7d3b-4a72-b792-20bd8d8fa069.storage.googleapis.com/s3fs-public/styles/max_650x650/public/2020-06/1_7LdK4cup8c8xRQzggtaP5Q.png?itok=Mvt-AQoZ',
	'2020-06-14T01:30:00Z',
	'Authored by Caitlin Johnstone via Medium.com,\r\nWikipedia, Facebook, Twitter, and mainstream media are falling all over themselves with censorship and spin jobs to get the narrative back under control… ',
	3),
	('Tyler Durden', 'Narrative Control Operations Escalate As America Burns',
	'Narrative Control Operations Escalate As America Burns\n\n Tyler Durden\n \nSat, 06/13/2020 - 21:30\n\n Authored by Caitlin Johnstone via Medium.com,\r\n\n\nWikipedia, Facebook, Twitter, and mainstream media are falling all over themselves with censorship and spin jobs…',
	'https://www.zerohedge.com/political/narrative-control-operations-escalate-america-burns',
	'https://zh-prod-1cc738ca-7d3b-4a72-b792-20bd8d8fa069.storage.googleapis.com/s3fs-public/styles/max_650x650/public/2020-06/1_7LdK4cup8c8xRQzggtaP5Q.png?itok=Mvt-AQoZ',
	'2020-06-14T01:30:00Z',
	'Authored by Caitlin Johnstone via Medium.com,\r\nWikipedia, Facebook, Twitter, and mainstream media are falling all over themselves with censorship and spin jobs to get the narrative back under control… ',
	4),
	('Tyler Durden', 'Narrative Control Operations Escalate As America Burns',
	'Narrative Control Operations Escalate As America Burns\n\n Tyler Durden\n \nSat, 06/13/2020 - 21:30\n\n Authored by Caitlin Johnstone via Medium.com,\r\n\n\nWikipedia, Facebook, Twitter, and mainstream media are falling all over themselves with censorship and spin jobs…',
	'https://www.zerohedge.com/political/narrative-control-operations-escalate-america-burns',
	'https://zh-prod-1cc738ca-7d3b-4a72-b792-20bd8d8fa069.storage.googleapis.com/s3fs-public/styles/max_650x650/public/2020-06/1_7LdK4cup8c8xRQzggtaP5Q.png?itok=Mvt-AQoZ',
	'2020-06-14T01:30:00Z',
	'Authored by Caitlin Johnstone via Medium.com,\r\nWikipedia, Facebook, Twitter, and mainstream media are falling all over themselves with censorship and spin jobs to get the narrative back under control… ',
	5),


	SELECT * FROM CurrentWeather
